### ISSUE TITLE
lock/unlock is quite slow

### ISSUE THREAD

**Issue by Fandekasp** [karulont/i3lock-blur#18]
It takes me 3\~4 secs to lock the screen, and 6\~9secs to unlock it.

Arch linux
i3-gaps-next-git 4.14.30
i3lock-blur 2.9-1
Running `i3lock -f -r 12 -s 12 -u && echo mem > /sys/power/state`
`i3lock -f -r 12 -s 12 -u -n` is also very slow.

I cannot find any related log, not sure how to fix this issue. Do you have any idea ?

**Comment by karulont** [comment]
Are you running a composer? Usually that is the problem.

**Comment by karulont** [comment]
Also i3lock in general seems to have problems with Compton for example see this: https://github.com/i3/i3lock/issues/141

**Comment by Fandekasp** [comment]
Yes, I'm running compton. And indeed i3lock wasn't especially fast, but not really comparable to i3lock-blur (was taking ~2s to lock/unlock, never more than 3).

Anyways, thanks for the tip, I fixed my issue with this script:

```
#!/usr/bin/env bash
set -eu

[[ -z "$(pgrep i3lock)" ]] || exit
#i3lock -n -u -t -i ${HOME}/.config/i3lock/lock.png
pkill compton
i3lock -f -r 12 -s 12 -u -n
compton -b
```
