### ISSUE TITLE
Not blurring feh background image

### ISSUE THREAD

**Issue by rubbateckie** [karulont/i3lock-blur#9]
When I run "i3lock -f" with applications running the result is what I expect. However, if I have no applications opened and can only see my background (produced by feh in i3), I see a blurred back background (with my i3bar at the bottom) when running "i3lock -f".

**Comment by karulont** [comment]
The bug is confirmed. The root window content is not copied to the texture that is used for blurring.

**Comment by karulont** [comment]
Essentially a one line fix.
